### ISSUE TITLE
Bug in launching script?

### ISSUE THREAD

**Issue by liar666** [Norconex/jef#1]
Hi,

I've made ./jef-monitor.sh executable. When I run it, I get an error:
 log4j:ERROR Could not read configuration file from URL [file:/./classes/log4j.properties].
java.io.FileNotFoundException: /./classes/log4j.properties (No such file or directory)

Indeed, file "jef-monitor.sh" reads:
export ROOT_DIR=$(dirname $0)
java ... "file:///${ROOT_DIR}/classes/..." ... 

Since I run from current directory, "ROOT_DIR" is ".", thus leading to a logging configuration file "file:///./classes/...", that Java translates to "/./classes/...". Since is it not a valid file, java cannot find it and complains.

I think the correct line in "jef-monitor.sh" should be:
export ROOT_DIR=$(realpath $(dirname $0))

**Comment by essiembre** [comment]
I have applied your suggestion.  You can find it in this new [snapshot release](https://www.norconex.com/jef/monitor/download).

Please confirm.

**Comment by essiembre** [comment]
Fix now in JEF Monitor 4.0.4 release : http://www.norconex.com/jef/monitor/download
