### ISSUE TITLE
Dialog/boxes too small / not resizeable :{

### ISSUE THREAD

**Issue by liar666** [Norconex/jef#4]
Hi,

During "Initial Configuration" , in the "Jobs to monitor" boxes, I can't read/check the pathes I've added as they are quite long. The dialog box to select the path is OK but the list is too small and cannot be resized :[

Also, when selecting "Add a file", the dialog box takes ages to open. And when it closes, the whole site is greyed out for ages too :{

**Comment by essiembre** [comment]
Try the latest [snapshot release](https://www.norconex.com/jef/monitor/download).  It is now possible to get the full path when doing a mouseover (a tooltip will appear after a second or two).  Let me know if that works for you.  I added a TODO in the application to revisit this screen to always show the full paths in a future release.

As for the delays, I suspect it takes a while to obtain the proper information from the filesystem.  Not sure why as I cannot reproduce. Do you have network mounts maybe?  If this get too problematic for you, we can make it a feature request to be able to simply enter a path and bypass the file dialog altogether.  This may be a good option regardless.

Please use the right project to report JEF Monitor issues in the future:  https://github.com/Norconex/jef-monitor

**Comment by essiembre** [comment]
Fix now in JEF Monitor 4.0.4 release : http://www.norconex.com/jef/monitor/download
